Added dependency for stetho and initialised it
fossasia/susi_android pull request #2371
Opened 2019-09-03 17:46 UTC by KKS161994

Fixes #2368

2019-09-03 17:50 UTC, iamareebjamal requested changes
Add OkHTTP interceptor and all other integrations

2019-09-04 18:35 UTC, KKS161994 commented
Can you please let me know if their are some other changes that I need to do.

2019-09-05 03:55 UTC, iamareebjamal commented on app/src/main/java/org/fossasia/susi/ai/MainApplication.kt
> +        OkHttpClient.Builder().addNetworkInterceptor(StethoInterceptor()).build()
Won't work. Please ensure it works before sending PR

2019-09-06 19:27 UTC, KKS161994 commented
Sir I have added NetworkInterceptor, Js module, dumpapp, local storage module of stetho. Is their anything more to add sir.
I have tested it from terminal using ./dumpapp and also using inspector of chrome for network requests and local storage.

2019-09-06 20:09 UTC, iamareebjamal commented on app/build.gradle
> +    implementation 'com.facebook.stetho:stetho-js-rhino:1.4.2'
Should only be enabled in debug build

2019-09-06 21:01 UTC, KKS161994 commented
Sir I have added it as a debug implementation and also the no-op part for stetho so that it doesn't fail for release build too.
releaseCompile "net.igenius:stetho-no-op:1.1"
Above is no-op library for stetho .

2019-09-07 04:39 UTC, iamareebjamal commented on app/src/main/java/org/fossasia/susi/ai/MainApplication.kt
> +                        .build())
Use initializeWithDefaults

2019-09-07 08:44 UTC, KKS161994 commented
Sir to use Stetho.initialisewithdefaults() I have to use a different no-op library since the older one didn't have initialiseWithdefaults() as a  member method. The new library has it included with other methods too.

2019-09-07 08:53 UTC, iamareebjamal commented
https://github.com/iamareebjamal/stetho-noop

2019-09-07 09:16 UTC, KKS161994 commented
> https://github.com/iamareebjamal/stetho-noop
> 
> > <img alt="" width="48" src="https://avatars1.githubusercontent.com/u/3874064?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[iamareebjamal/stetho-noop](https://github.com/iamareebjamal/stetho-noop)**Facebook stetho no-op for release build. Contribute to iamareebjamal/stetho-noop development by creating an account on GitHub.

Sir I integrated it for release implementation .

2019-09-07 09:41 UTC, iamareebjamal commented on app/build.gradle
> +    debugImplementation "com.facebook.stetho:stetho-js-rhino:${rootConfiguration.stehtoJsRhinoVersion}"
This isn't required

2019-09-07 09:42 UTC, iamareebjamal commented on app/config.gradle
> +    jitpackVersion = "1.1"
There is no library named 'jitpack'

Also, this section id only for dependencies with duplicate versions

2019-09-07 14:46 UTC, KKS161994 commented
Sir I have removed the js module of Stetho. And also the version numbers that I added. Okhttp dependency is a must to have for monitoring network requests made.

2019-09-07 17:46 UTC, iamareebjamal approved these changes

2019-09-07 17:46 UTC, iamareebjamal requested changes

2019-09-07 17:46 UTC, iamareebjamal commented on app/build.gradle
> +    debugImplementation "com.facebook.stetho:stetho-okhttp3:1.5.1"
This version is duplicate. Add it to the versions

2019-09-07 18:45 UTC, KKS161994 commented
Created a version name in the versions for Stetho and stetho ok http sir.

2019-09-08 07:12 UTC, iamareebjamal approved these changes

2019-09-08 07:12 UTC, merged